version: '3'

services:
  english:
    build: .
    command: bash "./docker_entrypoint.sh"
    volumes:
      - .:/i-dont-speak-english
    ports:
      - "5000:5000"
    networks:
      - database_network
    depends_on:
      - englishdb

  englishdb:
    image: postgres:10
    env_file:
      - bilgiler/database_env
    networks:
      - database_network
    volumes:
      - database_volume:/var/lib/postgresql/data

networks:
  database_network:
    driver: bridge

volumes:
  database_volume: