"""empty message

Revision ID: 93638a2e2417
Revises: a26bd26ff0a2
Create Date: 2019-11-03 16:46:48.585701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93638a2e2417'
down_revision = 'a26bd26ff0a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'user', ['user_id'], ['id'])
    op.drop_column('posts', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author', sa.VARCHAR(length=20), nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'user_id')
    # ### end Alembic commands ###
